name: remote ssh command
on:  
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/DibDibDotNet/DibDibDotNet 
          git status
          git add -A
          git commit -a -m "update database before merge"
          git push
          git pull
          docker-compose up --build -d
