name: remote ssh command
on:  
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host:  188.166.179.41
        username: root
        password: DibDib2021DotNet
        port: 22
        script: cd /root/DibDibDotNet/DibDibDotNet |
                docker-compose up --build -d
